import type { FighterDefinition } from "./types";

export const ATLAS_LION: FighterDefinition = {
  id: "atlas-lion",
  displayName: "Atlas Lion",
  maxHealth: 1000,
  walkSpeed: 4,
  jumpVelocity: -14,
  hurtbox: { x: -24, y: -118, width: 48, height: 118 },
  moves: {
    light: {
      id: "light",
      state: "lightAttack",
      duration: 18,
      damage: 45,
      hitstun: 14,
      blockstun: 8,
      pushback: 10,
      attackerFreeze: 3,
      defenderFreeze: 5,
      meterGainOnUse: 16,
      meterGainOnHit: 72,
      meterGainOnBlock: 34,
      hitVolumes: [{ frameStart: 5, frameEnd: 8, rect: { x: 18, y: -96, width: 42, height: 22 } }],
    },
    lightKick: {
      id: "lightKick",
      state: "lightKick",
      duration: 22,
      damage: 58,
      hitstun: 16,
      blockstun: 9,
      pushback: 12,
      attackerFreeze: 3,
      defenderFreeze: 5,
      meterGainOnUse: 18,
      meterGainOnHit: 84,
      meterGainOnBlock: 38,
      hitVolumes: [{ frameStart: 7, frameEnd: 11, rect: { x: 18, y: -62, width: 52, height: 24 } }],
    },
    heavy: {
      id: "heavy",
      state: "heavyAttack",
      duration: 30,
      damage: 90,
      hitstun: 22,
      blockstun: 13,
      pushback: 18,
      attackerFreeze: 5,
      defenderFreeze: 8,
      meterGainOnUse: 28,
      meterGainOnHit: 118,
      meterGainOnBlock: 58,
      hitVolumes: [{ frameStart: 10, frameEnd: 15, rect: { x: 22, y: -104, width: 58, height: 28 } }],
    },
    special: {
      id: "special",
      state: "specialAttack",
      duration: 42,
      damage: 120,
      hitstun: 30,
      blockstun: 18,
      pushback: 28,
      attackerFreeze: 6,
      defenderFreeze: 10,
      meterGainOnUse: 42,
      meterGainOnHit: 148,
      meterGainOnBlock: 82,
      hitVolumes: [{ frameStart: 14, frameEnd: 21, rect: { x: 30, y: -92, width: 76, height: 34 } }],
    },
    super: {
      id: "super",
      state: "superAttack",
      duration: 62,
      damage: 260,
      hitstun: 42,
      blockstun: 28,
      pushback: 42,
      attackerFreeze: 9,
      defenderFreeze: 14,
      meterGainOnUse: 0,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      hitVolumes: [{ frameStart: 18, frameEnd: 32, rect: { x: 20, y: -112, width: 122, height: 58 } }],
    },
  },
};

export const SAHARA_VIPER: FighterDefinition = {
  ...ATLAS_LION,
  id: "sahara-viper",
  displayName: "Sahara Viper",
  walkSpeed: 4.35,
  hurtbox: { x: -22, y: -112, width: 44, height: 112 },
};

export const GRAY_RABBIT: FighterDefinition = {
  ...ATLAS_LION,
  id: "gray-rabbit",
  displayName: "Gray Rabbit",
  walkSpeed: 4.45,
  jumpVelocity: -15.25,
  hurtbox: { x: -21, y: -114, width: 42, height: 114 },
  moves: {
    ...ATLAS_LION.moves,
    lightKick: {
      ...ATLAS_LION.moves.lightKick,
      damage: 62,
      pushback: 14,
      hitVolumes: [{ frameStart: 6, frameEnd: 11, rect: { x: 20, y: -70, width: 58, height: 26 } }],
    },
    heavy: {
      ...ATLAS_LION.moves.heavy,
      damage: 88,
      pushback: 20,
      hitVolumes: [{ frameStart: 10, frameEnd: 16, rect: { x: 24, y: -100, width: 60, height: 30 } }],
    },
    special: {
      ...ATLAS_LION.moves.special,
      damage: 118,
      pushback: 34,
      hitVolumes: [{ frameStart: 12, frameEnd: 24, rect: { x: 28, y: -104, width: 84, height: 48 } }],
    },
  },
};

export const GINGER_TABBY_CAT: FighterDefinition = {
  ...ATLAS_LION,
  id: "ginger-tabby-cat",
  displayName: "Ginger Tabby Cat",
  walkSpeed: 4.65,
  jumpVelocity: -14.6,
  hurtbox: { x: -23, y: -112, width: 46, height: 112 },
  moves: {
    ...ATLAS_LION.moves,
    light: {
      ...ATLAS_LION.moves.light,
      duration: 17,
      damage: 42,
      meterGainOnUse: 17,
      hitVolumes: [{ frameStart: 4, frameEnd: 8, rect: { x: 18, y: -92, width: 46, height: 22 } }],
    },
    heavy: {
      ...ATLAS_LION.moves.heavy,
      damage: 94,
      pushback: 16,
      hitVolumes: [{ frameStart: 9, frameEnd: 15, rect: { x: 20, y: -108, width: 64, height: 30 } }],
    },
    special: {
      ...ATLAS_LION.moves.special,
      damage: 126,
      hitstun: 32,
      pushback: 26,
      hitVolumes: [{ frameStart: 13, frameEnd: 22, rect: { x: 24, y: -112, width: 92, height: 40 } }],
    },
  },
};

export const PICKLES_PUGILIST: FighterDefinition = {
  ...ATLAS_LION,
  id: "pugilist-pug",
  displayName: "Pickles Pugilist",
  walkSpeed: 4.1,
  jumpVelocity: -13.8,
  hurtbox: { x: -24, y: -104, width: 48, height: 104 },
  moves: {
    ...ATLAS_LION.moves,
    light: {
      ...ATLAS_LION.moves.light,
      duration: 16,
      damage: 40,
      hitstun: 15,
      blockstun: 9,
      pushback: 8,
      meterGainOnUse: 18,
      hitVolumes: [{ frameStart: 4, frameEnd: 8, rect: { x: 16, y: -86, width: 38, height: 24 } }],
    },
    lightKick: {
      ...ATLAS_LION.moves.lightKick,
      damage: 50,
      pushback: 10,
      hitVolumes: [{ frameStart: 7, frameEnd: 11, rect: { x: 14, y: -50, width: 44, height: 22 } }],
    },
    heavy: {
      ...ATLAS_LION.moves.heavy,
      duration: 28,
      damage: 86,
      hitstun: 24,
      blockstun: 15,
      pushback: 12,
      hitVolumes: [{ frameStart: 9, frameEnd: 15, rect: { x: 18, y: -90, width: 50, height: 32 } }],
    },
    special: {
      ...ATLAS_LION.moves.special,
      damage: 116,
      hitstun: 34,
      blockstun: 20,
      pushback: 20,
      hitVolumes: [{ frameStart: 12, frameEnd: 22, rect: { x: 18, y: -94, width: 68, height: 36 } }],
    },
    super: {
      ...ATLAS_LION.moves.super,
      damage: 248,
      pushback: 34,
      hitVolumes: [{ frameStart: 17, frameEnd: 32, rect: { x: 18, y: -102, width: 100, height: 54 } }],
    },
  },
};

export const NOODLE_NIBBLES: FighterDefinition = {
  ...ATLAS_LION,
  id: "ferret-noodle",
  displayName: "Noodle Nibbles",
  walkSpeed: 4.75,
  jumpVelocity: -14.35,
  hurtbox: { x: -26, y: -106, width: 52, height: 106 },
  moves: {
    ...ATLAS_LION.moves,
    light: {
      ...ATLAS_LION.moves.light,
      duration: 15,
      damage: 38,
      hitstun: 14,
      blockstun: 9,
      pushback: 9,
      meterGainOnUse: 20,
      hitVolumes: [{ frameStart: 4, frameEnd: 8, rect: { x: 18, y: -82, width: 48, height: 24 } }],
    },
    lightKick: {
      ...ATLAS_LION.moves.lightKick,
      duration: 21,
      damage: 52,
      hitstun: 17,
      blockstun: 11,
      pushback: 16,
      hitVolumes: [{ frameStart: 6, frameEnd: 11, rect: { x: 20, y: -48, width: 58, height: 22 } }],
    },
    heavy: {
      ...ATLAS_LION.moves.heavy,
      duration: 29,
      damage: 84,
      hitstun: 24,
      blockstun: 15,
      pushback: 18,
      hitVolumes: [{ frameStart: 9, frameEnd: 15, rect: { x: 16, y: -86, width: 78, height: 30 } }],
    },
    special: {
      ...ATLAS_LION.moves.special,
      duration: 40,
      damage: 112,
      hitstun: 34,
      blockstun: 20,
      pushback: 30,
      meterGainOnUse: 46,
      hitVolumes: [{ frameStart: 12, frameEnd: 23, rect: { x: 12, y: -76, width: 102, height: 38 } }],
    },
    super: {
      ...ATLAS_LION.moves.super,
      damage: 242,
      pushback: 40,
      hitVolumes: [{ frameStart: 16, frameEnd: 32, rect: { x: 10, y: -94, width: 132, height: 52 } }],
    },
  },
};
