import type { FighterDefinition } from "./types";

export const ATLAS_LION: FighterDefinition = {
  id: "atlas-lion",
  displayName: "Atlas Lion",
  maxHealth: 1000,
  walkSpeed: 4,
  jumpVelocity: -14,
  hurtbox: { x: -24, y: -118, width: 48, height: 118 },
  moves: {
    light: {
      id: "light",
      state: "lightAttack",
      duration: 18,
      damage: 45,
      hitstun: 14,
      blockstun: 8,
      pushback: 10,
      attackerFreeze: 3,
      defenderFreeze: 5,
      meterGainOnUse: 16,
      meterGainOnHit: 72,
      meterGainOnBlock: 34,
      hitVolumes: [{ frameStart: 5, frameEnd: 8, rect: { x: 18, y: -96, width: 42, height: 22 } }],
    },
    lightKick: {
      id: "lightKick",
      state: "lightKick",
      duration: 22,
      damage: 58,
      hitstun: 16,
      blockstun: 9,
      pushback: 12,
      attackerFreeze: 3,
      defenderFreeze: 5,
      meterGainOnUse: 18,
      meterGainOnHit: 84,
      meterGainOnBlock: 38,
      hitVolumes: [{ frameStart: 7, frameEnd: 11, rect: { x: 18, y: -62, width: 52, height: 24 } }],
    },
    heavy: {
      id: "heavy",
      state: "heavyAttack",
      duration: 30,
      damage: 90,
      hitstun: 22,
      blockstun: 13,
      pushback: 18,
      attackerFreeze: 5,
      defenderFreeze: 8,
      meterGainOnUse: 28,
      meterGainOnHit: 118,
      meterGainOnBlock: 58,
      hitVolumes: [{ frameStart: 10, frameEnd: 15, rect: { x: 22, y: -104, width: 58, height: 28 } }],
    },
    special: {
      id: "special",
      state: "specialAttack",
      duration: 42,
      damage: 120,
      hitstun: 30,
      blockstun: 18,
      pushback: 28,
      attackerFreeze: 6,
      defenderFreeze: 10,
      meterGainOnUse: 42,
      meterGainOnHit: 148,
      meterGainOnBlock: 82,
      hitVolumes: [{ frameStart: 14, frameEnd: 21, rect: { x: 30, y: -92, width: 76, height: 34 } }],
    },
    super: {
      id: "super",
      state: "superAttack",
      duration: 62,
      damage: 260,
      hitstun: 42,
      blockstun: 28,
      pushback: 42,
      attackerFreeze: 9,
      defenderFreeze: 14,
      meterGainOnUse: 0,
      meterGainOnHit: 0,
      meterGainOnBlock: 0,
      hitVolumes: [{ frameStart: 18, frameEnd: 32, rect: { x: 20, y: -112, width: 122, height: 58 } }],
    },
  },
};

export const SAHARA_VIPER: FighterDefinition = {
  ...ATLAS_LION,
  id: "sahara-viper",
  displayName: "Sahara Viper",
  walkSpeed: 4.35,
  hurtbox: { x: -22, y: -112, width: 44, height: 112 },
};
